import assert from 'node:assert/strict';
import { readdirSync, readFileSync } from 'node:fs';
const migrationsDir=new URL('../migrations/',import.meta.url);
const migrationNames=readdirSync(migrationsDir).filter(name=>name.endsWith('.sql')).sort();
const combined=migrationNames.map(name=>readFileSync(new URL(name,migrationsDir),'utf8')).join('\n');
const workerGateName=migrationNames.find(name=>name.includes('script_worker_completion_gate'));
const identityConcurrencyName=migrationNames.find(name=>name.includes('identity_intake_concurrency_completion'));
assert.ok(workerGateName,'script worker completion migration must exist');
assert.ok(identityConcurrencyName,'identity intake concurrency migration must exist');
const workerGate=readFileSync(new URL(workerGateName,migrationsDir),'utf8');
const identityConcurrency=readFileSync(new URL(identityConcurrencyName,migrationsDir),'utf8');
assert.match(combined,/creator_private\.consent_statements/is,'consent must be bound to server-known evidence');
assert.match(combined,/creator_private\.rights_statements/is,'content-rights statements must be governed server evidence');
assert.match(combined,/42250e837adc94788c9a403c5e49362eac5c6914279ba74bfdc83c588bc2cb80/i,'content-rights digest must be governed');
assert.match(combined,/extensions\.digest/is,'artifact authority must recompute text digests');
assert.match(combined,/ARTIFACT_DIGEST_MISMATCH/is,'mismatched caller digest must fail closed');
assert.match(combined,/creator_private\.transition_claims/is,'transition idempotency must bind to exact operation payload');
assert.match(combined,/v_project\.title <> v_title/is,'project request replay must bind to exact title');
assert.match(combined,/on conflict \(owner_id, client_request_id\) do nothing/is,'concurrent project retries must recover through the unique request key');
assert.match(combined,/v_existing\.details->>'target_kind'.*p_target_kind/is,'revision replay must bind to target kind');
assert.match(combined,/v_existing\.details->>'reason'.*v_reason/is,'revision/revoke replay must bind to exact reason');
assert.match(combined,/creator_stage_rank\(v_project\.current_stage\).*v_target_rank/is,'revision targets must not jump to unreached workflow stages');
assert.match(combined,/REVISION_TARGET_NOT_REACHED/is,'forward revision attempts must fail closed');
assert.match(combined,/IDEMPOTENCY_KEY_REUSED/is,'conflicting replay must be rejected');
assert.match(combined,/creator_upload_intents/is,'prepared uploads must be tracked');
assert.match(combined,/creator_prepare_identity_upload/is,'server-authoritative upload preparation must exist');
assert.match(combined,/UPLOAD_INTENT_REQUIRED/is,'registration must bind to a prepared intent');
assert.match(combined,/UPLOAD_INTENT_EXPIRED/is,'expired intents must fail registration');
assert.match(combined,/PRIVATE_OBJECT_NOT_FOUND/is,'physical object must exist before registration or validation');
assert.match(combined,/creator_storage_upload_allowed/is,'Storage insert must serialize upload intent/profile state');
assert.match(combined,/for key share/is,'Storage upload must lock the profile before accepting media');
assert.match(combined,/creator_begin_delete_consent_profile/is,'deletion must have a begin phase');
assert.match(combined,/creator_finalize_delete_consent_profile/is,'deletion must have a finalize phase');
assert.match(combined,/status = 'deleting'/is,'delete begin must tombstone the profile before media cleanup');
assert.match(combined,/revoke all on function public\.creator_delete_consent_profile\(uuid,uuid\) from authenticated/is,'legacy one-phase delete must not be browser executable');
assert.match(combined,/PRIVATE_MEDIA_DELETE_REQUIRED/is,'final deletion must fail closed while tracked media exists');
assert.match(combined,/creator_private\.operation_claims/is,'destructive idempotency keys must be claimed before mutation');
assert.match(combined,/creator_invalidate_profile_dependents/is,'revocation/deletion require full downstream invalidation');
assert.match(combined,/from public\.creator_projects p[\s\S]*order by p\.id[\s\S]*for update/is,'profile invalidation must lock affected projects before artifact/review mutation');
assert.match(combined,/creator_reviews r[\s\S]*invalidated_at/is,'downstream reviews must be invalidated');
assert.match(combined,/job_type in \('voice','avatar','edit','final'\)/is,'voice revocation must cancel downstream jobs');
assert.match(combined,/then 'SCRIPT_APPROVED'/is,'voice revocation must rewind project stage');
assert.match(combined,/then 'VOICE_APPROVED'/is,'avatar revocation must rewind project stage');
assert.match(combined,/object_path=null.*sha256=null/is,'deletion must clear sensitive sample metadata');
assert.match(workerGate,/creator_record_script_draft/is,'M2 must provide a trusted SCRIPT_READY completion path');
assert.match(workerGate,/revoke all on function public\.creator_record_script_draft\(uuid,text,text,uuid\) from public, anon, authenticated/is,'browser roles must not complete script generation');
assert.match(workerGate,/grant execute on function public\.creator_record_script_draft\(uuid,text,text,uuid\) to service_role/is,'trusted worker role must be able to complete script generation');
assert.match(workerGate,/'SCRIPT_READY'[\s\S]*'SCRIPT_REVIEW'/is,'trusted completion must move script generation to human review');
assert.doesNotMatch(workerGate,/\('SCRIPT_APPROVED','START_VOICE'/i,'M2 must not expose START_VOICE before a trusted voice-ready path exists');
assert.doesNotMatch(workerGate,/\('VOICE_APPROVED','START_AVATAR'/i,'M2 must not expose START_AVATAR before a trusted avatar-ready path exists');
assert.doesNotMatch(workerGate,/\('AVATAR_APPROVED','START_EDIT'/i,'M2 must not expose START_EDIT before a trusted edit-ready path exists');
assert.doesNotMatch(workerGate,/\('EDIT_APPROVED','START_FINAL'/i,'M2 must not expose START_FINAL before a trusted final-ready path exists');
assert.match(identityConcurrency,/creator_create_consent_profile_impl[\s\S]*on conflict \(owner_id, client_request_id\) do nothing/is,'consent-profile retries must recover concurrent unique conflicts');
assert.match(identityConcurrency,/creator_prepare_identity_upload_impl[\s\S]*for key share[\s\S]*on conflict \(owner_id, client_request_id\) do nothing/is,'upload preparation must lock the profile first and recover concurrent request conflicts');
assert.match(identityConcurrency,/creator_register_identity_sample_impl[\s\S]*for key share[\s\S]*for update/is,'sample registration must lock the profile before the upload intent');
assert.doesNotMatch(combined,/getPublicUrl/i,'M2 must not introduce public media URLs');
console.log('M2 consent/storage/workflow authority static guardrails: PASS');
