import type { SupabaseClient } from '@supabase/supabase-js';
import { NextResponse } from 'next/server';
import { ArtifactViewSchema,ProjectViewSchema,type ArtifactView,type ProjectView } from '@creator/contracts';
import { createCreatorSupabaseServerClient } from '../supabase/server';
export class CreatorHttpError extends Error{constructor(readonly status:number,readonly code:string,message:string){super(message);this.name='CreatorHttpError';}}
export type CreatorAuthority=Readonly<{client:SupabaseClient;userId:string}>;
export async function requireCreatorAuthority():Promise<CreatorAuthority>{let client:SupabaseClient;try{client=await createCreatorSupabaseServerClient();}catch{throw new CreatorHttpError(503,'AUTHORITY_UNAVAILABLE','Creator Studio authority is not configured.');}const {data,error}=await client.auth.getClaims();const subject=data?.claims?.sub;if(error||typeof subject!=='string'||subject.length===0)throw new CreatorHttpError(401,'AUTHENTICATION_REQUIRED','Sign in is required.');return{client,userId:subject};}
export async function readJsonBody(request:Request):Promise<unknown>{try{return await request.json();}catch{throw new CreatorHttpError(400,'INVALID_JSON','The request body is not valid JSON.');}}
export async function projectIdFromContext(context:Readonly<{params:Promise<{projectId:string}>}>):Promise<string>{const{projectId}=await context.params;if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(projectId))throw new CreatorHttpError(400,'PROJECT_ID_INVALID','The project ID is invalid.');return projectId;}
function asRecord(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw new CreatorHttpError(502,'AUTHORITY_RESPONSE_INVALID','Authority returned an invalid response.');return value as Record<string,unknown>;}
function nullableString(value:unknown):string|null{return typeof value==='string'?value:null;}
function requiredString(record:Record<string,unknown>,key:string):string{const value=record[key];if(typeof value!=='string')throw new CreatorHttpError(502,'AUTHORITY_RESPONSE_INVALID','Authority returned an invalid response.');return value;}
function requiredPositiveInteger(record:Record<string,unknown>,key:string):number{const value=record[key];if(!Number.isInteger(value)||Number(value)<=0)throw new CreatorHttpError(502,'AUTHORITY_RESPONSE_INVALID','Authority returned an invalid response.');return Number(value);}
export function serializeProject(value:unknown):ProjectView{const r=asRecord(value);return ProjectViewSchema.parse({id:requiredString(r,'id'),title:requiredString(r,'title'),currentStage:requiredString(r,'current_stage'),createdAt:nullableString(r.created_at),updatedAt:nullableString(r.updated_at)});}
export function serializeArtifact(value:unknown):ArtifactView{const r=asRecord(value);return ArtifactViewSchema.parse({id:requiredString(r,'id'),kind:requiredString(r,'kind'),version:requiredPositiveInteger(r,'version_number'),sha256:requiredString(r,'sha256'),inlineText:nullableString(r.inline_text),staleAt:nullableString(r.stale_at),createdAt:nullableString(r.created_at)});}
export function readRpcEnvelope(value:unknown):Readonly<{project:ProjectView;artifact:ArtifactView;replayed:boolean}>{const r=asRecord(value);return{project:serializeProject(r.project),artifact:serializeArtifact(r.artifact),replayed:r.replayed===true};}
const CLIENT_ERROR_CODES=new Set([
'ACTIVE_VOICE_PROFILE_REQUIRED','APPROVAL_BINDING_REQUIRED','ARTIFACT_BINDING_INVALID','ARTIFACT_DIGEST_MISMATCH','ARTIFACT_ID_INVALID','ARTIFACT_KIND_NOT_ENABLED','ARTIFACT_TEXT_INVALID',
'CLIENT_REQUEST_ID_REQUIRED','CONSENT_EVIDENCE_INVALID','CONSENT_NOT_CURRENT','FILE_NAME_INVALID','FILE_SIZE_INVALID','HUMAN_APPROVAL_REQUIRED','HUMAN_TRIGGER_REQUIRED','IDEMPOTENCY_KEY_REQUIRED','IDEMPOTENCY_KEY_REUSED',
'INVALID_WORKFLOW_TRANSITION','LATEST_ARTIFACT_REQUIRED','MEDIA_DELETE_LEASE_INVALID','MEDIA_DELETE_NOT_CLAIMED','MEDIA_DELETE_NOT_CLAIMABLE','MIME_TYPE_NOT_ALLOWED','MOCK_PROVIDER_MUST_BE_ZERO_COST',
'MOCK_PROVIDER_NOT_APPROVED','MOCK_RUNTIME_MODE_REQUIRED','PRIVATE_MEDIA_DELETE_REQUIRED','PRIVATE_OBJECT_NOT_FOUND','PROFILE_DELETED','PROFILE_DELETE_IN_PROGRESS','PROFILE_DELETE_NOT_PREPARED','PROFILE_KIND_INVALID',
'PROFILE_NAME_INVALID','PROFILE_NOT_AVAILABLE','PROJECT_TITLE_INVALID','REVISION_REASON_INVALID','REVISION_TARGET_INVALID','REVISION_TARGET_NOT_REACHED','RIGHTS_ATTESTATION_REQUIRED','RIGHTS_STATEMENT_INVALID','SCRIPT_APPROVAL_REQUIRED',
'SHA256_INVALID','STAGE_CONFLICT','SYNTHETIC_LABEL_REQUIRED','TEXT_ARTIFACT_PATH_FORBIDDEN','UPLOAD_INTENT_CORRUPT','UPLOAD_INTENT_EXPIRED','UPLOAD_INTENT_NOT_AVAILABLE','UPLOAD_INTENT_REQUIRED','VALIDATED_SAMPLE_REQUIRED',
'VOICE_BUDGET_INVALID','VOICE_GENERATION_MODE_INVALID','VOICE_JOB_AUTHORITY_MISMATCH','VOICE_JOB_NOT_CLAIMABLE','VOICE_JOB_NOT_COMPLETABLE','VOICE_LEASE_CAPABILITY_INVALID','VOICE_LEASE_INVALID','VOICE_LEASE_STATE_INVALID',
'VOICE_MANIFEST_DIGEST_INVALID','VOICE_OBJECT_BINDING_INVALID','VOICE_OBJECT_METADATA_MISMATCH','VOICE_OUTPUT_DIGEST_INVALID','VOICE_OUTPUT_METADATA_INVALID','VOICE_PREVIEW_FORBIDDEN','VOICE_PROVIDER_NOT_FOUND',
'VOICE_PROVIDER_SNAPSHOT_STALE','VOICE_RUNTIME_POLICY_UNAVAILABLE'
]);
function authorityErrorCode(message:string):string|null{for(const code of CLIENT_ERROR_CODES)if(message.includes(code))return code;if(message.includes('PROJECT_NOT_FOUND'))return'PROJECT_NOT_FOUND';if(message.includes('PROFILE_NOT_FOUND'))return'PROFILE_NOT_FOUND';if(message.includes('SAMPLE_NOT_FOUND'))return'SAMPLE_NOT_FOUND';if(message.includes('VOICE_JOB_NOT_FOUND'))return'VOICE_JOB_NOT_FOUND';if(message.includes('MEDIA_DELETE_NOT_FOUND'))return'MEDIA_DELETE_NOT_FOUND';return null;}
export function throwForRpcError(error:Readonly<{message:string}>|null):void{if(!error)return;const code=authorityErrorCode(error.message);if(code==='PROJECT_NOT_FOUND'||code==='PROFILE_NOT_FOUND'||code==='SAMPLE_NOT_FOUND'||code==='VOICE_JOB_NOT_FOUND'||code==='MEDIA_DELETE_NOT_FOUND')throw new CreatorHttpError(404,code,'Requested Creator Studio resource was not found.');if(code)throw new CreatorHttpError(409,code,'The requested creator action is not allowed.');throw new CreatorHttpError(502,'AUTHORITY_REQUEST_FAILED','Creator authority rejected the request.');}
export function creatorErrorResponse(error:unknown):NextResponse{if(error instanceof CreatorHttpError)return NextResponse.json({error:error.message,code:error.code},{status:error.status});return NextResponse.json({error:'Creator Studio request failed.',code:'INTERNAL_ERROR'},{status:500});}
